version: '3.8'

services:
  servers:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    container_name: dad
    command: >
      bash -c '
      mvn clean install &&
      cd server &&
      mvn exec:java -Dexec.args="8080 0"'
