package dadkvs.server;

/* these imported classes are generated by the contract */
import dadkvs.server.domain.ServerState;
import dadkvs.DadkvsConsole;
import dadkvs.DadkvsConsoleServiceGrpc;
import io.grpc.stub.StreamObserver;

public class ConsoleServiceImpl extends DadkvsConsoleServiceGrpc.DadkvsConsoleServiceImplBase {

	private ServerState _serverState;

	public ConsoleServiceImpl(final ServerState state) {
		this._serverState = state;
	}

	@Override
	public void setleader(final DadkvsConsole.SetLeaderRequest request,
			final StreamObserver<DadkvsConsole.SetLeaderReply> responseObserver) {
		// for debug purposes
		System.out.println(request);

		final boolean responseValue = true;
		_serverState.setLeader(request.getIsleader());

		final DadkvsConsole.SetLeaderReply response = DadkvsConsole.SetLeaderReply.newBuilder()
				.setIsleaderack(responseValue).build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
		_serverState.logSystem.writeLog("Set leader request completed");
	}

	@Override
	public void setdebug(final DadkvsConsole.SetDebugRequest request,
			final StreamObserver<DadkvsConsole.SetDebugReply> responseObserver) {
		// for debug purposes
		System.out.println(request);

		final boolean responseValue = true;

		_serverState.setDebugMode(request.getMode());

		final DadkvsConsole.SetDebugReply response = DadkvsConsole.SetDebugReply.newBuilder()
				.setAck(responseValue).build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
		_serverState.logSystem.writeLog("Set debug request completed");
	}
}
