package dadkvs.server;

/* these imported classes are generated by the contract */
import dadkvs.server.domain.ServerState;
import dadkvs.DadkvsConsole;
import dadkvs.DadkvsConsoleServiceGrpc;
import io.grpc.stub.StreamObserver;

public class ConsoleServiceImpl extends DadkvsConsoleServiceGrpc.DadkvsConsoleServiceImplBase {

	ServerState serverState;

	public ConsoleServiceImpl(final ServerState state) {
		this.serverState = state;
	}

	@Override
	public void setleader(final DadkvsConsole.SetLeaderRequest request,
			final StreamObserver<DadkvsConsole.SetLeaderReply> responseObserver) {
		// for debug purposes
		System.out.println(request);

		final boolean responseValue = true;
		if (request.getIsleader()) {
			serverState.paxosState.promote();
		} else {
			serverState.paxosState.demote();
		}
		this.serverState.iAmLeader = request.getIsleader();

		// for debug purposes
		System.out.println("I am the leader = " + this.serverState.iAmLeader);
		serverState.logSystem.writeLog("I am the leader = " + this.serverState.iAmLeader);

		final DadkvsConsole.SetLeaderReply response = DadkvsConsole.SetLeaderReply.newBuilder()
				.setIsleaderack(responseValue).build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
		serverState.logSystem.writeLog("Set leader request completed");
	}

	@Override
	public void setdebug(final DadkvsConsole.SetDebugRequest request,
			final StreamObserver<DadkvsConsole.SetDebugReply> responseObserver) {
		// for debug purposes
		System.out.println(request);

		final boolean responseValue = true;

		this.serverState.debugMode = request.getMode();

		// for debug purposes
		System.out.println("Setting debug mode to = " + this.serverState.debugMode);
		serverState.logSystem.writeLog("Setting debug mode to = " + this.serverState.debugMode);

		final DadkvsConsole.SetDebugReply response = DadkvsConsole.SetDebugReply.newBuilder()
				.setAck(responseValue).build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
		serverState.logSystem.writeLog("Set debug request completed");
	}
}
