package dadkvs.server;

/* these imported classes are generated by the contract */
import dadkvs.DadkvsFastPaxos;
import dadkvs.DadkvsFastPaxosServiceGrpc;

import io.grpc.stub.StreamObserver;

public class DadkvsFastPaxosServiceImpl extends DadkvsFastPaxosServiceGrpc.DadkvsFastPaxosServiceImplBase {

	DadkvsServerState server_state;

	public DadkvsFastPaxosServiceImpl(DadkvsServerState state) {
		this.server_state = state;
	}

	@Override
	public void fastpaxos(DadkvsFastPaxos.FastPaxosRequest request,
			StreamObserver<DadkvsFastPaxos.FastPaxosReply> responseObserver) {
		// for debug purposes
		System.out.println(request);

		// TODO: send request to all other replicas with the reqId
		server_state.orderRequest(request.getReqId(), request.getEpoch());

		DadkvsFastPaxos.FastPaxosReply response = DadkvsFastPaxos.FastPaxosReply.newBuilder().build();

		responseObserver.onNext(response);
	}

}
