package dadkvs.server;

/* these imported classes are generated by the contract */
import dadkvs.DadkvsMain;
import dadkvs.DadkvsMainServiceGrpc;
import io.grpc.stub.StreamObserver;

public class DadkvsMainServiceImpl extends DadkvsMainServiceGrpc.DadkvsMainServiceImplBase {
	static final int SERVER_DELAY = 3000; // 3 seconds
	private final DadkvsServerState _serverState;

	int timestamp;

	public DadkvsMainServiceImpl(final DadkvsServerState state) {
		this._serverState = state;
		this.timestamp = 0;
	}

	public void trySleep() {
		try {
			Thread.sleep((int) (SERVER_DELAY * (Math.random() + 0.5))); // Median is SERVER_DELAY
		} catch (final InterruptedException e) {
		}
	}

	public void checkConsoleRequest(final int reqId) {
		if (reqId % 100 != 0) { // NOTE: its not a console request
			synchronized (_serverState.freezeLock) {
				while (_serverState.frozen) {
					try {
						_serverState.freezeLock.wait();
					} catch (final InterruptedException e) {
					}
				}
			}
			if (_serverState.slowMode) {
				trySleep();
			}
		}
	}

	@Override
	public void read(final DadkvsMain.ReadRequest request, final StreamObserver<DadkvsMain.ReadReply> responseObserver) {
		// for debug purposes
		System.out.println("Receiving read request:" + request);
		_serverState.logSystem.writeLog("Receiving read request");

		final int reqId = request.getReqid();
		final int key = request.getKey();

		checkConsoleRequest(reqId);

		final VersionedValue vv = _serverState.store.read(key);
		final DadkvsMain.ReadReply response = DadkvsMain.ReadReply.newBuilder()
				.setReqid(reqId).setValue(vv.getValue()).setTimestamp(vv.getVersion()).build();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
		_serverState.logSystem.writeLog("Read request completed");
	}

	@Override
	public void committx(final DadkvsMain.CommitRequest request,
			final StreamObserver<DadkvsMain.CommitReply> responseObserver) {
		_serverState.logSystem.writeLog("Received commit request");

		final int reqId = request.getReqid();
		final int key1 = request.getKey1();
		final int version1 = request.getVersion1();
		final int key2 = request.getKey2();
		final int version2 = request.getVersion2();
		final int writekey = request.getWritekey();
		final int writeval = request.getWriteval();

		checkConsoleRequest(reqId);

		_serverState.paxosState.handleCommittx(reqId);

		// for debug purposes
		_serverState.logSystem
				.writeLog("reqId " + reqId + " key1 " + key1 + " v1 " + version1 + " k2 " + key2 + " v2 " + version2
						+ " wk " + writekey + " writeval " + writeval);
		System.out.println("reqId " + reqId + " key1 " + key1 + " v1 " + version1 + " k2 " + key2 + " v2 " + version2
				+ " wk " + writekey + " writeval " + writeval);

		_serverState.logSystem.writeLog("Waiting for sequence number");
		final int seqNumber = _serverState.getSequenceNumber(reqId);
		_serverState.logSystem.writeLog("COMMITING: " + seqNumber);

		_serverState.waitInLine(seqNumber);
		timestamp++;

		final TransactionRecord txrecord = new TransactionRecord(key1, version1, key2, version2, writekey, writeval,
				timestamp);

		final boolean result = _serverState.store.commit(txrecord);

		final DadkvsMain.CommitReply response = DadkvsMain.CommitReply.newBuilder()
				.setReqid(reqId).setAck(result).build();

		_serverState.logSystem.writeLog(_serverState.store.toString());
		_serverState.nextInLine();

		responseObserver.onNext(response);
		responseObserver.onCompleted();
	}
}
